// -------------------------------------------------------------
// 
// File Name: hdlsrc\AddMul\Adder_Multiplier_HDL.v
// Created: 2026-01-09 15:43:48
// 
// Generated by MATLAB 9.11 and HDL Coder 3.19
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Adder_Multiplier_HDL
// Source Path: AddMul/Adder_Multiplier_HDL
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Adder_Multiplier_HDL
          (A,
           B,
           Sout,
           Pout);


  input   [2:0] A;  // ufix3
  input   [2:0] B;  // ufix3
  output  [3:0] Sout;  // ufix4
  output  [5:0] Pout;  // ufix6


  wire [3:0] Add_1;  // ufix4
  wire [3:0] Add_2;  // ufix4
  wire [3:0] Add_out1;  // ufix4
  wire [5:0] Product_out1;  // ufix6


  assign Add_1 = {1'b0, A};
  assign Add_2 = {1'b0, B};
  assign Add_out1 = Add_1 + Add_2;


  assign Sout = Add_out1;

  assign Product_out1 = A * B;


  assign Pout = Product_out1;

endmodule  // Adder_Multiplier_HDL

